[package]
name = "rouille"
version = "1.0.3"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tomaka/rouille"
documentation = "http://docs.rs/rouille"
description = "High-level idiomatic web framework."
readme = "README.md"
keywords = ["web", "framework", "http", "rest"]
categories = ["web-programming::http-server", "web-programming::websocket"]

[features]
default = ["gzip", "brotli", "rustc-serialize"]
brotli = ["brotli2"]
gzip = ["flate2"]
serdejson = ["serde", "serde_derive", "serde_json"]

[dependencies]
base64 = "0.7.0"
brotli2 = { version = "0.2.1", optional = true }
chrono = "0.4.0"
filetime = "0.1.10"
flate2 = { version = "0.2.14", optional = true }
multipart = { version = "0.5.1", default-features = false, features = ["server"] }
rand = "0.3.11"
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
sha1 = "0.2.0"
term = "0.2"
time = "0.1.31"
tiny_http = "0.5.6"
url = "1.2"

[dev-dependencies]
postgres = { version = "0.13", default-features = false }
log = "0.3"
